name: pykan-env
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - python==3.9.18
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - cpuonly
  - torchaudio
  - torchvision
  - matplotlib
  - tqdm
  - hyperopt
  - xarray
  - shap
  - snakemake-minimal
  - graphviz
  - pip
  - pip: 
    - pykan


